---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: blog/posts/dexter
  label: Dexter
  create: documents
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: bash ./deploy.sh
  preview_output_directory: ".vuepress/dist"
  output_directory: "/docs"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
  preview_docker_image: node:10
  mount_path: "/srv"
